### ISSUE TITLE
extending support to iterable objects ?

### ISSUE THREAD

**Issue by wryk** [dpolac/twig-lambda#1]
Sadly, underscore-php use native array_\* functions and doesn't allow to use an object implementing an iterable interface. Is it out of context for this library to add such feature ?

example use case : working out of the box with doctrine collections (and equivalents) without transformation to a native array before

**Comment by dpolac** [comment]
Thank you. I have overlooked that. It is important, as I intend to use that with doctrine collections too. I will add that soon.

**Comment by dpolac** [comment]
Filters now support all Traversable objects.
