### ISSUE TITLE
`group_by` not working when grouping by objects

### ISSUE THREAD

**Issue by palra** [dpolac/twig-lambda#2]
When using the `group_by` filter, grouping by objects, I get an exception of illegal offset type, because of that line : https://github.com/dpolac/twig-lambda/blob/master/LambdaExtension.php#L149
Example : 

``` twig
{% for key, group in array|group_by(=> _.associatedEntity) %}
  = {{ key.name }}
  {% for i in group %}
    * {{ group.name }}
  {% endfor }%
{% endfor %}
```

A possible workaround would be to use an [SplObjectStorage](http://php.net/manual/en/class.splobjectstorage.php) instead of an array for `$results`, but it implies using `offsetGet()` and `offsetSet()` instead of regular `[]` operator.

By the way, great extension :+1:

**Comment by dpolac** [comment]
Thank you for suggestion. I created new release with support for grouping by objects.

It calls lambda once and check if result is object or scalar. For scalar, it returns regular array like before and for object it returns Iterator. Note that Iterator with objects as keys is probably not compatible with other filters, so don't chain it like:

`array|group_by(=> _.associatedEntity)|filter(=> _|length > 3)  !!! error`

(You can still do that when grouping by scalar.)
I will think about solution for that later.

Let me know if you find any issue in the future.

**Comment by palra** [comment]
Works like a charm, thanks ! :smile:
