### ISSUE TITLE
`unique` casts array elements to string when checking uniqueness

### ISSUE THREAD

**Issue by palra** [dpolac/twig-lambda#3]
When doing something like :

``` twig
{% for key, group in array|map(=> _.associatedEntity)|unique %}
    {# ... #}
{% endfor %}
```

I get an error stating that `associatedEntity`'s class could not be converted to a string. The thing is that `array_unique()` casts every element of the array as string by default. I tested by passing as a 2nd argument to `array_unique` `SORT_REGULAR` (as by default it is `SORT_STRING`) and it works for my specific case. I don't see where it could fail for every other "regular" cases.

**Comment by dpolac** [comment]
Thank you for pointing that out.

`array_unique` with `SORT_REGULAR` uses `==` operator, so in some situations it may be not very useful when using with array of objects.
I've written new filter `unique_by`. You can also use `|unique_by('==')` for effect similar to `SORT_REGULAR` and `|unique_by('===')` . You can also use that with lambda like: `|unique_by((a;b) => a.name == b.name)`.
