### ISSUE TITLE
Twig version constraint "^1.0"

### ISSUE THREAD

**Issue by Jibato** [dpolac/twig-lambda#7]
Hi,

Thanks for your great work!
Would it be possible to change the twig version constraint from "^1.0" to ">=1.0" or "1 - 2" as there are no deprecated features for Twig 2.x?
With actual setting I'm back to Twig 1.33.0 from 2.1.0 before using your bundle.

Regards

**Comment by alpha1917** [comment]
AFAIK there is at least this depreciated method [https://github.com/dpolac/twig-lambda/blob/703d4440f986035c9010163c79a4afc78894ab80/NodeExpression/Lambda.php#L21](https://github.com/dpolac/twig-lambda/blob/703d4440f986035c9010163c79a4afc78894ab80/NodeExpression/Lambda.php#L21)

**Comment by Jibato** [comment]
Oups, my mistake! I read the 2.x deprecated list instead of 1.x ...

**Comment by dpolac** [comment]
@Jibato You can now use Twig-Lambda with Twig 2.x. Just update package to 1.0. Sorry for huge delay.

**Comment by Jibato** [comment]
Thank you so much @dpolac !
